version: '3.8'

services:
  app:
    build: .
    environment:
      DB_DRIVER: postgres
      DB_USER: #user
      DB_PASSWORD: #dbpwd
      DB_HOST: #host
      DB_PORT: #port
      DB_NAME: #corsedev
    ports:
      - "8085:8085"
