version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1001
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_DRIVER: postgres
      DB_USER: postgres
      DB_PASSWORD: 1001
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: postgres
    volumes:
      - .:/app
    working_dir: /app
